#!/bin/sh

# Hook script to view mime-encoded content.
# Copy to the directory ~/.csup/hooks .
#
# Read one line containing the content type.
#
# If the content type is recognized, pass the remainder
# of the input to the appropriate viewing program, and return
# the exit status of the viewing program.
#
# Otherwise ignore the content, and return a non-zero exit status.

view () {
  viewer=$1
  t=$(mktemp) || exit 1
  trap "rm -f -- '$t'" EXIT
  cat >$t
  $viewer $t
  status=$?
  rm -f -- "$t"
  trap - EXIT
  exit $status
}

read type
#echo "mime-view: type = $type" >>/tmp/csup.log
case $type in
#text/html)
#  echo "mime-view: running w3m" >>/tmp/csup.log
#  cat - | w3m -T text/html
#  echo "mime-view: done running w3m" >>/tmp/csup.log
#  ;;
#text/plain)
#  cat
#  ;;
*/pdf)
  view xreader
  ;;
image/*)
  view xviewer
  ;;
*)
  exit 1
  ;;
esac
